config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/auth/google_oauth2/callback', to: 'sessions#create_with_google_oauth'

  resources :laboratories do 
    resources :appointments
  end

  resources :users
  resources :laboratories
  resources :appointments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :type_of_appt, :appt_time, :appt_date, presence: true
  validates :laboratory_id, presence: true
  belongs_to :user, optional: true
  belongs_to :laboratory, optional: true

  scope :order_by_date, -> {order(:appt_date)}
  scope :order_by_lab, -> {order(:laboratory_id)}

  def laboratory_attributes=(laboratory_attributes)
    if !laboratory_attributes[:name].empty?
      laboratory = Laboratory.find_or_create_by(name: laboratory_attributes[:name],lab_type: laboratory_attributes[:lab_type], phone_number: laboratory_attributes[:phone_number], address: laboratory_attributes[:address], lab_hours: laboratory_attributes[:lab_hours], days_of_operation: laboratory_attributes[:days_of_operation])
      laboratory.appointments << self
    end
  end
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
  validates :name, :lab_type, :phone_number, :address, :lab_hours, :days_of_operation, presence: true
  has_many :appointments
  has_many :users, through: :appointments

  accepts_nested_attributes_for :appointments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :first_name, :last_name, presence: true
  validates :email, uniqueness: true
  validates :password, length: { in: 6..20 }
  validates :password_confirmation, presence: true

  has_many :appointments
  has_many :laboratories, through: :appointments
  accepts_nested_attributes_for :appointments, :allow_destroy => true

  scope :order_by_birthdate, -> {order(:birthdate)}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :logged_in?

  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_laboratory
  # skip_before_action :find_laboratory, only: [:index, :show]
  
  def index
    if @laboratory
      @appointments = @laboratory.appointments.where(user_id: @user.id)
    else
      @appointments = @user.appointments.all
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def new
    @appointment = Appointment.new
  end

  def create
    if @laboratory
      @appointment = @laboratory.appointments.create(appointment_params)
    else
      @appointment = Appointment.create(appointment_params)
      @laboratory = @appointment.laboratory
    end
    if @appointment.valid?
      redirect_to laboratory_appointment_path(@laboratory, @appointment)
    else
      render :new
    end
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.find(params[:id])
    @appointment.update(appointment_params)
    if @appointment.valid?
      redirect_to appointment_path(@appointment)
    else
      render :edit
    end
  end

  def destroy
    Appointment.find(params[:id]).destroy
    redirect_to appointments_path
  end

  private

  def set_laboratory
    @laboratory = Laboratory.find_by_id(params[:laboratory_id])
  end

  def appointment_params
    params.require(:appointment).permit(:type_of_appt, :appt_time, :appt_date, :laboratory_id, 
    laboratory_attributes: [ :name, :lab_type, :phone_number, :address, :lab_hours, :days_of_operation] ).merge(user_id: current_user.id)
  end
end

app/controllers/laboratories_controller.rb
class LaboratoriesController < ApplicationController
  before_action :set_laboratory, only: [:show]
  
  def index
    @laboratories = Laboratory.all
  end

  def show
    @appointments = @laboratory.appointments
  end

  def new
    @laboratory = Laboratory.new
  end

  def create
    @laboratory = Laboratory.create(lab_params)
    if @laboratory.valid?
      redirect_to laboratories_path
    else
      render :new
    end
  end

  private

  def set_laboratory
    @laboratory = Laboratory.find(params[:id])
  end

  def lab_params
    params.require(:laboratory).permit(:name, :lab_type, :phone_number, :address, :lab_hours, :days_of_operation, :appointment_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :create_with_google_oauth]

  def new
    if logged_in?
      redirect_to user_path(current_user)
    end
  end


  def create_with_google_oauth
    omniauth = request.env['omniauth.auth']
    @user = User.find_or_create_by!(email: omniauth['info']['email']) do |u|
        u.first_name = omniauth['info']['first_name']
        u.last_name = omniauth['info']['last_name']
        u.password = SecureRandom.hex(10)
        u.password_confirmation = u.password
      end
      session[:user_id] = @user.id
      redirect_to user_path(@user)
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:errors] = ['Incorrect username or password']
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user.update(user_params)
    if @user.valid?
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :birthdate, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/laboratories_helper.rb
module LaboratoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_apptfields.html.erb
<%= f.label :type_of_appt %>
<%= f.text_field :type_of_appt %>
<br>
<%= f.label :appt_time %>
<%= f.text_field :appt_time %>
<br>
<%= f.label :appt_date %>
<%= f.text_field :appt_date %>
<br>
<br>

app/views/appointments/_form.html.erb
<%= form_for [@laboratory, @appointment]  do |f| %>

<% if @appointment.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(@appointment.errors.count, "error" ) %> did'nt allow your form to save.</h3>
    <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render partial:"apptfields", locals:{f: f} %>

<% if @laboratory.nil? %>
  <p>Pick existing Lab</p>
  <%= render partial:"laboratories/labselect", locals:{f: f} %>

  <% if false %>
    <p>Or add a new Laboratory</p>
    <%= f.fields_for :laboratory , @appointment.build_laboratory do |lab| %>
      <%= render partial:"laboratories/labfields", locals: {lab: lab} %>
    <% end %>
  <% end %>

<% end %>

<br>
<br>
  
  <%= f.submit %>
<% end %>
<br>

app/views/appointments/edit.html.erb
<h1>Edit <%= @appointment.type_of_appt %> appointment.</h1>
<%= form_for @appointment do |f| %>

  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@appointment.errors.count, "error" ) %> did'nt allow your form to save.</h3>
      <ul>
        <% @appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :type_of_appt %>
  <%= f.text_field :type_of_appt %>
  <br>
  <%= f.label :appt_time %>
  <%= f.text_field :appt_time %>
  <br>
  <%= f.label :appt_date %>
  <%= f.text_field :appt_date %>
<br>
<br>
<%= f.submit %>
<% end %>

<p><%= link_to "Profile", user_path(@user)%></p>

app/views/appointments/index.html.erb
<h1>Scheduled appointments for <%= @user.first_name %>.</h1>
<p><strong>Hint: </strong>You can click on the appointment to go to that page, as well as the lab name.</p>

<ul>
  <% @appointments.each do |appt| %>
    <li>Appointment for: <%= link_to appt.type_of_appt, laboratory_appointment_path(appt.laboratory.id, appt.id) %></li>
    <li>Time: <%= appt.appt_time %></li>
    <li>Date: <%= appt.appt_date %></li>
    <li>Lab: <%= link_to appt.laboratory.name, laboratory_path(appt.laboratory) %></li>
  <% end %>
</ul>


<br>
<p><%= link_to "Profile", user_path(@user)%></p>

app/views/appointments/new.html.erb
<h1>Schedule a new appointment</h1>

<%= render 'form' %>

<%= link_to "User profile", @user %>

<br>

app/views/appointments/show.html.erb
<h2><%= @user.first_name %>, your appointment info.</h2>

  <p>Appointment type: <%= @appointment.type_of_appt %></p>
  <p>Appointment time: <%= @appointment.appt_time %></p>
  <p>Appointment date: <%= @appointment.appt_date %></p>
  <p>Verify patient last name: <%= @appointment.user.last_name %></p>
  <p>Verify correct laboratory: <%= @appointment.laboratory.name %></p>

<br>
<%= link_to "Profile", user_path(@user)%> | <%= link_to "Get #{@appointment.laboratory.name} info", laboratory_path(@appointment.laboratory.id) %> | <%= link_to "Edit appointment", edit_appointment_path(@appointment)%>

<br>
<br>
<%= button_to "Remove appointment", appointment_path(@appointment), method: :delete %>

app/views/laboratories/_form.html.erb
<%= form_for @laboratory do |f| %>

<% if @laboratory.errors.any? %>
  <div id="errors_explanation">
    <h3><%= pluralize(@laboratory.errors.count, 'error') %> did'nt allow your form to save</h3>
    <% @laboratory.errors.full_messages.each do |message| %>
      <ul>
        <li><%= message %></li>
      </ul>
    <% end %>
  </div>
<% end %>

<%= render partial:"labfields", locals: {lab: f} %>

<%= f.submit %>
<% end %>

app/views/laboratories/_labfields.html.erb
  
  <%= lab.label :name %>
  <%= lab.text_field :name %>
  <br>
  <%= lab.label :lab_type %>
  <%= lab.text_field :lab_type %>
  <br>
  <%= lab.label :phone_number %>
  <%= lab.text_field :phone_number %>
  <br>
  <%= lab.label :address %>
  <%= lab.text_field :address %>
  <br>
  <%= lab.label :lab_hours %>
  <%= lab.text_field :lab_hours %>
  <br>
  <%= lab.label :days_of_operation %>
  <%= lab.text_field :days_of_operation %>
  <br>
  <br>

app/views/laboratories/_labselect.html.erb
<%= f.label :laboratory_id %>
  <%= f.collection_select :laboratory_id, Laboratory.all, :id, :name, include_blank: "Choose Lab" %>

app/views/laboratories/index.html.erb
<h2>Local Labs</h2>
<p>** click on a lab to create a new appointment</p>

<% @laboratories.each do |lab| %>

<ul>
  <li><%= link_to lab.name, new_laboratory_appointment_path(lab.id) %></li>
</ul>

<% end %>

<p><%= link_to "Profile", user_path(@user)%></p>

app/views/laboratories/new.html.erb
<h1>Create a new Laboratory</h1>

<%= render 'form' %>


<p><%= link_to "Profile", user_path(@user)%></p>

app/views/laboratories/show.html.erb
<h2>Welcome to <%= @laboratory.name %> Lab page!</h2>

<h4>Lab Name: <%= @laboratory.name %></h4>
<h4>Type: <%= @laboratory.lab_type %></h4>
<h4>Phone number: <%= number_to_phone(@laboratory.phone_number) %></h4>
<h4>Address: <%= @laboratory.address %></h4>
<h4>Days available: <%= @laboratory.days_of_operation %></h4>
<p><%= link_to "#{@laboratory.name}", laboratory_appointments_path(@laboratory) %> scheduled appointments.</p>



<p><%= link_to "Profile", user_path(@user)%></p>
<p><%= link_to "Add appointment", new_laboratory_appointment_path(@laboratory) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabsAndThings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="content">
    <%= yield %>
    <br>
    <% if logged_in? %>
       <span class="logout"><%= button_to "Logout", logout_path %></span>
    <% end %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(@user.errors.count, "error" ) %> didnt allow your form to save.</h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>
  <%= f.label :birthdate %>
  <%= f.date_select :birthdate, {order: [:month, :day, :year], prompt: { day: 'Select day', month: 'Select month', year: 'Select year' }, start_year: 1900, end_year: Time.now.year }, {required: true} %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit %>
<% end  %>
  <br>

app/views/users/edit.html.erb
<h2>Edit your profile for <%= @user.first_name.capitalize %></h2>

<%= render 'form' %>

<p><%= link_to "Go back", user_path(@user)%></p>

app/views/users/new.html.erb
<h1>Sign up here</h1>

<h3>Enter all your info to create a profile.</h3>

<%= render 'form' %>

<%= link_to "Sign in",  login_path %>

app/views/users/show.html.erb
<h1>You are now logged in <%= @user.first_name.capitalize if @user.first_name %> <%= @user.last_name %>.</h1>

<p class="intro">Welcome to your profile. Your information is displayed here for you to see.</p>

<div class="user-data">
  <h2>Patient section.</h2>

  <h4>Patient email: <%= @user.email %></h4>
  <h4>Patient last name: <%= @user.last_name %></h4>
<% if @user.birthdate %>
  <h4>Patient birtdate: <%= @user.birthdate.strftime("%B %d, %Y") %></h4>
<% end %>

  <span><%= link_to "Edit profile", edit_user_path(@user) %></span>

<br>


<div class="user-appts">
  <h2>Appointments section.</h2>

  <% if !@user.appointments.empty? %>
    <h3>Total appointments pending: <%= @user.laboratories.uniq.count %></h3>
    <%= link_to "Appointments page", appointments_path %> | 
    <%= link_to "Add appointment", new_appointment_path %>
  <% else %>
    <h3>You're all caught up with appointments this month. Great job.<h3>
    <%= link_to "Add a new appointment", new_appointment_path(@user)%> 
  <% end %>
<br>



<br>

<div class="user-labs">

  <h2>Patient laboratories section.</h2>
  <p>Click on the laboratory name to visit its information page and view your appointments.</p>

  <ul>
    <% @user.laboratories.uniq.each do |lab| %>
      <li>Laboratory name: <%= link_to lab.name, laboratory_appointments_path(lab) %></li>
      <li>Type: <%= lab.lab_type %></li>
      <li>Phone: <%= number_to_phone(lab.phone_number) %></li>
    <% end %>
  </ul>

<%= link_to "New Lab", new_laboratory_path %> | <%= link_to "New appointment w/ Lab", laboratories_path %>

</div>
</div>
</div>
<br>